"""Initial migration 1

Revision ID: bbdbb9088682
Revises: a7bfd42631e5
Create Date: 2024-06-10 19:32:17.974880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdbb9088682'
down_revision: Union[str, None] = 'a7bfd42631e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_words_german', table_name='words')
    op.drop_index('ix_words_id', table_name='words')
    op.drop_table('words')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=1)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('german', sa.VARCHAR(), nullable=True),
    sa.Column('russian', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('user_word_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_words_id', 'words', ['id'], unique=False)
    op.create_index('ix_words_german', 'words', ['german'], unique=False)
    # ### end Alembic commands ###
